#Runs the predict.py script in the opt/timed-design directory. Must specify path to the hdf5 file 
#generated by aposteriori as well as the output directory. 


python /opt/timed-design/predict.py  \
    --path_to_dataset   \
    --path_to_model  \
    --path_to_output 